---
- name: tap caskroom/cask so that brew-cask can be installed
  homebrew_tap: tap=caskroom/cask state=present

- name: install/update brew cask
  homebrew: name=brew-cask state=latest

- name: install/update cask apps
  homebrew_cask: name={{ item }} state=present
  with_items: cask
  when: cask is defined
